version: "3.9"

services:
  moodfit-app:
    build: .
    container_name: moodfit_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=production
    restart: unless-stopped
